# Where the homeserver is located (client-server URL). This should point at
# pantalaimon if you're using that.
homeserverUrl: "https://matrix.org"

# The access token for the bot to use. Do not populate if using Pantalaimon.
accessToken: "YOUR_TOKEN_HERE"

# Pantalaimon options (https://github.com/matrix-org/pantalaimon)
pantalaimon:
  # If true, accessToken above is ignored and the username/password below will be
  # used instead. The access token of the bot will be stored in the dataPath.
  use: false

  # The username to login with.
  username: mjolnir

  # The password to login with. Can be removed after the bot has logged in once and
  # stored the access token.
  password: your_password

# The directory the bot should store various bits of information in
dataPath: "/data/storage"

# Whether the bot should autojoin rooms it is invited to or not
autojoin: true

# The room ID where people can use the bot. The bot has no access controls, so
# anyone in this room can use the bot - secure your room!
# This should be a room alias or room ID - not a matrix.to URL.
managementRoom: "#moderators:example.org"

# The room ID or alias where the bot's own personal ban list is kept. This is
# where the commands to manage a ban list end up being routed to. Note that
# this room is NOT automatically added to the banLists list below - you will
# need to add it yourself!
publishedBanListRoom: "#banlist:example.org"

# A list of rooms to protect (matrix.to URLs)
protectedRooms:
  - "https://matrix.to/#/#yourroom:example.org"

# A list of ban lists to follow (matrix.to URLs)
banLists:
  - "https://matrix.to/#/#sample-ban-list:t2bot.io" # S.A.M.P.L.E.
